// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

// Protobuf Java Version: 3.25.9
package helixflo.example.grpc;

public final class GreeterProto {
  private GreeterProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helixflo_example_grpc_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helixflo_example_grpc_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_helixflo_example_grpc_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_helixflo_example_grpc_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rgreeter.proto\022\025helixflo.example.grpc\"\034" +
      "\n\014HelloRequest\022\014\n\004name\030\001 \001(\t\"\035\n\nHelloRep" +
      "ly\022\017\n\007message\030\001 \001(\t2]\n\007Greeter\022R\n\010SayHel" +
      "lo\022#.helixflo.example.grpc.HelloRequest\032" +
      "!.helixflo.example.grpc.HelloReplyB\'\n\025he" +
      "lixflo.example.grpcB\014GreeterProtoP\001b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_helixflo_example_grpc_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_helixflo_example_grpc_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helixflo_example_grpc_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_helixflo_example_grpc_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_helixflo_example_grpc_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_helixflo_example_grpc_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
